---
# Import Library

---

In [ ]:
# untuk pengolahan Data dan menampilkan data dalam bentuk DataFrame.
import pandas as pd

# untuk perhitungan matematika.
import numpy as np

# untuk split dataset train & test.
from sklearn.model_selection import train_test_split

# untuk handle Outlier.
# from feature_engine.outliers import Winsorizer

# untuk Scaling data. (Numeric - Skew)
# from sklearn.preprocessing import MinMaxScaler

# untuk Encode data. (Categorical - Nominal)
# from sklearn.preprocessing import OneHotEncoder

# Menghitung kolerasi antar kolom.
# import phik

# Model Machine Learning yang akan dipakai.
# from sklearn.linear_model import LogisticRegression
# from sklearn.tree import DecisionTreeClassifier
# from sklearn.ensemble import RandomForestClassifier

# untuk menghitung hasil predict model dan visualisasi dengan bentuk heatmap.
# from sklearn.metrics import recall_score, confusion_matrix, ConfusionMatrixDisplay

# Untuk Model Saving.
# import pickle

# untuk menghilangkan result dengan warning.
import warnings
warnings.filterwarnings("ignore")

---
# Data Loading

---

In [64]:
Data = pd.read_csv('order_agg_modeling_v0_1.csv', index_col=0)
Backup_data = Data.copy()

In [65]:
# untuk memunculkan semua kolom.
pd.options.display.max_columns = None

# Contoh Data yang akan dipakai.
Data.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,total_items,total_order_value,total_freight,avg_item_price,payment_type,total_payment_value,max_installments,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,is_canceled
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,29.99,8.72,29.99,voucher,38.71,1.0,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,0
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1.0,118.70,22.76,118.70,boleto,141.46,1.0,af07308b275d755c9edb36a90c618231,47813,barreiras,BA,0
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1.0,159.90,19.22,159.90,credit_card,179.12,3.0,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO,0
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,1.0,45.00,27.20,45.00,credit_card,72.20,1.0,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN,0
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,1.0,19.90,8.72,19.90,credit_card,28.62,1.0,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP,0

---
# Feature Engineering

---

---
## Duplicated Check

---

In [66]:
# Check Data Duplikat
print(f"Data duplicate : {Data.duplicated().sum()}")
print(f"Total Data : {Data.shape[0]}")

Data duplicate : 0
Total Data : 98832

Seems the data cleaned from duplicated records, we can move forward to the next step.

---
## Split column X & y

---

In [ ]:
# menghilangkan kolom primary key, candidate primary key, dan kolom target
X = Data.drop(columns=['customer_id','order_id','customer_unique_id','order_status','is_canceled'],axis=1)

# target prediksi adalah transaksi yang mungkin akan di canceled
y = Data.is_canceled

In [78]:
X.head()

,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,total_items,total_order_value,total_freight,avg_item_price,payment_type,total_payment_value,max_installments,customer_zip_code_prefix,customer_city,customer_state
0,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,29.99,8.72,29.99,voucher,38.71,1.0,3149,sao paulo,SP
1,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,1.0,118.70,22.76,118.70,boleto,141.46,1.0,47813,barreiras,BA
2,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,1.0,159.90,19.22,159.90,credit_card,179.12,3.0,75265,vianopolis,GO
3,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,1.0,45.00,27.20,45.00,credit_card,72.20,1.0,59296,sao goncalo do amarante,RN
4,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,1.0,19.90,8.72,19.90,credit_card,28.62,1.0,9195,santo andre,SP

In [72]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 98832 entries, 0 to 99440
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_status                   98832 non-null  object
 1   order_purchase_timestamp       98832 non-null  object
 2   order_approved_at              98672 non-null  object
 3   order_delivered_carrier_date   97658 non-null  object
 4   order_delivered_customer_date  96476 non-null  object
 5   order_estimated_delivery_date  98832 non-null  object
 6   total_items                    98660 non-null  float64
 7   total_order_value              98660 non-null  float64
 8   total_freight                  98660 non-null  float64
 9   avg_item_price                 98660 non-null  float64
 10  payment_type                   98831 non-null  object
 11  total_payment_value            98831 non-null  float64
 12  max_installments               98831 non-null  float64
 13  customer_zip_code_prefix       98832 non-null  int64
 14  customer_city                  98832 non-null  object
 15  customer_state                 98832 non-null  object
dtypes: float64(6), int64(1), object(9)
memory usage: 12.8+ MB

In [ ]:
num_col = ['total_items','total_order_value','total_freight','avg_item_price', 'total_payment_value', 'max_installments']
cat_col = ['payment_type','customer_state']
date_col = ['order_purchase_timestamp','order_approved_at'
            ,'order_delivered_carrier_date','order_delivered_customer_date','order_estimated_delivery_date']

---
## Missing value check

---

In [ ]:
Missing = Data.isnull().sum()
Only_Missing = Missing[Missing > 0].sort_values(ascending=False)

print(f"Data Missing : \n{Only_Missing}")

Data Missing :
order_delivered_customer_date    2356
order_delivered_carrier_date     1174
total_items                       172
total_order_value                 172
total_freight                     172
avg_item_price                    172
order_approved_at                 160
payment_type                        1
total_payment_value                 1
max_installments                    1
dtype: int64

In [ ]:
# mengelompokkan missing value pada "total_item" dengan "is_canceled" lalu menghitung "rata ratanya"
Data['total_items'].isna().groupby(Data['is_canceled']).mean()

is_canceled
0    0.000081
1    0.262400
Name: total_items, dtype: float64